### ISSUE TITLE
"[nodemon] app crashed - waiting for file changes before starting..."

### ISSUE THREAD

**Issue by CharlieJo42** [CharlieJo42/Unit2CodingProject#1]
I am trying to get "hello world" to render in the browser again.

When I run "npm run dev", it tried to run with a file name that doesn't exist anymore. 

--I fixed the name in package.json to match the name of the current file. This was the result:

>  events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: listen EADDRINUSE: address already in use :::3000
>     at Server.setupListenHandle [as _listen2] (net.js:1280:14)
>     at listenInCluster (net.js:1328:12)
>     at Server.listen (net.js:1415:7)
>     at Function.listen (/home/charliejo42/Desktop/Unit2Coding/node_modules/express/lib/application.js:618:24)
>     at Object.<anonymous> (/home/charliejo42/Desktop/Unit2Coding/server.js:9:5)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> Emitted 'error' event at:
>     at emitErrorNT (net.js:1307:8)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

VSCode registered an error on line 2 of package.json stating that "String does not match the pattern of "^(?:@[a-z0-9-*~][a-z0-9-*._~]*/)?[a-z0-9-~][a-z0-9-._~]*$"."

--I then made the name lowercase and the error disappeared from vscode. However, in the command line, it now reads:

> 

> events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: listen EADDRINUSE: address already in use :::3000
>     at Server.setupListenHandle [as _listen2] (net.js:1280:14)
>     at listenInCluster (net.js:1328:12)
>     at Server.listen (net.js:1415:7)
>     at Function.listen (/home/charliejo42/Desktop/Unit2Coding/node_modules/express/lib/application.js:618:24)
>     at Object.<anonymous> (/home/charliejo42/Desktop/Unit2Coding/server.js:9:5)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
> Emitted 'error' event at:
>     at emitErrorNT (net.js:1307:8)
>     at process._tickCallback (internal/process/next_tick.js:63:19)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3

)

and simply keeps crashing

I will likely just erase both the server.js and the package.json and retype them by hand, but I'm also curious to know what this error means and how to figure out where the issue is located. 

**When I go to "localhost:3000", it does say "Hello World," but that's if I type in "localhost:3000" manually from the browser, not by running a line in the commands.

**Comment by CharlieJo42** [comment]
change port to 3001
